site_name: MATRIX
theme: material
site_description: MATRIX OS Documentation
docs_dir: docs
extra_css: ['styles.css']

pages:
- Home: 'index.md'
- Intro - MATRIX OS: 'intro/matrix.md'
- Intro - MATRIX CLI: 'cli/overview.md'
- Intro - Low Level Interfaces: 'intro/interfaces.md'
- OS:
  - App API:
    - 'Overview': 'API/overview.md'
    - 'Computer Vision': 'API/computer-vision.md'
    - 'Crosstalk': 'API/crosstalk.md'
    - 'Type': 'API/typesend.md'
    - 'GPIO': 'API/GPIO.md'
    - 'Sensors': 'API/sensors.md'
    - 'Filters': 'API/filter.md'
    - 'Microphone': 'API/microphone.md'
    - 'IR TX/RX': 'API/ir.md'
    - 'Everloop': 'API/everloop.md'
    - 'NFC': 'API/nfc.md'
    - 'Z-wave': 'API/zwave.md'
    - 'Zigbee': 'API/zigbee.md'
  - Config:
    - 'Overview': 'Configuration/overview.md'
    - 'Datatypes': 'Configuration/datatypes.md'
    - 'Screens': 'Configuration/screens.md'
    - 'Filters': 'Configuration/filters.md'
    - 'Widgets': 'Configuration/widgets.md'
    - 'Services': 'Configuration/services.md'
    - 'Examples': 'Configuration/examples.md'
- CLI:
  - 'Overview': 'CLI/overview.md'
  - 'Apps': 'CLI/apps.md'
  - 'Examples': 'CLI/example.md'
- Hardware:
  - 'FPGA': 'Hardware/fpga.md'
  - 'SAM3': 'Hardware/Sam3.md'
  - 'SAM3MCU': 'Hardware/sam3mcu-programming.md'
  - 'Microphone': 'Hardware/microphone.md'
  - 'SPI': 'Hardware/SPI.md'
- Supporting Libraries:
  - 'HAL': 'intro/hal.md'
  - 'MALOS': 'intro/malos.md'
- Reference:
  - 'Overview': 'Reference/overview.md'
  - 'Pinout': 'Reference/pinout.md'
